github_repo: 'meteor'
description:
author:
language:
timezone:
apis:
  gtm: GTM-MBQ369M
  marketo: 627-RVJ-941
  segment: zQx6cQifkTU79E3L0XAnmrOXP2A5bC6r
  docsearch:
    apiKey: 85d8a989beb6790642e6edd6ea380788
    indexName: meteor

# For use with the "Edit on GitHub" button, this represents the path to the
# source markdown, from the root of the GitHub repository, with no leading
# slash.  It's set to 'source' here as that's the Hexo default, though it can
# vary based on repository configuration (some variations use the
# less-preferred `content` directory.
content_root: 'source'

css_bundle: meteor
nav_class: dark

favicon: images/favicon-meteor.png

logo:
  nav_mobile: images/meteor-logo.png
  url: ''
  title: 'Meteor Developers'
  subtitle: 'Developers'

nav_links:
  'Meteor Cloud':
    url: https://www.meteor.com/cloud
    partial: illustration-guide
    target: _new
    active: false
  'Tutorials':
    url: https://www.meteor.com/developers/tutorials
    partial: illustration-guide
    target: _new
    active: false
  'Guide':
    url: https://guide.meteor.com
    partial: illustration-compass
    active: false
  'API Docs':
    url: https://docs.meteor.com
    partial: illustration-logs
    active: false
  'Forums':
    url: https://forums.meteor.com/
    partial: illustration-support
    target: _new
    active: false

social_links:
  github: 'https://github.com/meteor'
  twitter: '@meteorjs'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

default_category: uncategorized
category_map:
tag_map:

date_format: YYYY-MM-DD
time_format: HH:mm:ss

per_page: 10
pagination_dir: page

theme: ../node_modules/@meteorjs/meteor-theme-hexo

# Match the GitHub style of breaks, since we generally do edits on GitHub.
marked:
  breaks: false

# Disable native Syntax highlighting, in order to allow Prism to work properly.
highlight:
  enable: false

# Now, enable Prism, for better syntax highlighting which supports things we
# need.  Note that individual syntax support is provided by the layout in the
# theme, located at https://github.com/meteor/meteor-theme-hexo.
prism_plus:
  enable: true
  mode: preprocess
  default_preset:
    # Line numbering on by default.
    lineno: true

deploy:
  type:

browsersync:
  ghostMode: false
